/* eslint-disable quotes */
export default {
    eligibaleErrorDateOfBirthNew:
        'You are not eligible for sign up due to age constraint. Age should be greater than {{_age}}',
    done: 'Done',
    emailSentSuccesfully: 'Email sent successfully',
    resetSuccesfully: 'Reset Succesfully',
    selectedAnswerSaveSuccefully: 'Selected answer save successfully',
    noChangeMade: 'No changes made',
    userUnsubSucc: 'User unsubscribe successfully',
    user: 'User',
    otpSendSuccessfully: 'OTP send successfully',
    pleaseEnterAtLeastEmailOrMobileOrBoth: 'Please enter at least email or mobile or both',
    userDoesNotExist: 'User does not exist',
    pleaseEnterEmailIdOrPhoneNumberWhichIsRegisteredWithOpinionBureau:
        'Please enter email or phone number which is registered with Opinion Bureau.',
    resetSucessfully: 'Reset Successfully',
    oldPassNotMatch: "Old password doesn't match",
    pointConvertRequestTimeLesser: 'Point convert request time lesser',
    totalPointConvertRequestInOneDayExceed: 'Total points convert request in one day exceed',
    youHaveLowBalance: 'You have low balance.',
    loadMore: 'Load more',
    editYourProfile: 'Edit your profile',
    contactInformation: 'Contact information',
    address: 'Address',
    addressLine1: 'Line 1(Suite/Apartment/House No)',
    addressLine2: 'Line 2(Street Address)',
    postCodeZipCode: 'Post Code/ Zip Code',
    enterPostCodeZipCode: 'enter post code/ zip code',
    selectState: 'select state',
    stateAndProvince: 'State/Province',
    redeemed: 'Redeemed',
    qualifiedApprovedNew: 'Qualified-Approved',
    qualifiedRejectedNew: 'Qualified-Rejected',
};
