const data = {
    totalcount: 25,
    data: [
        {
            profile_survey_question_id: '43',
            question_id: 463,
            order_no: 1,
            question: 'Highest Level of Education',
            question_type: '2',
            answer_arr: [
                { question_answer_id: 3974, answer: 'Illiterate' },
                { question_answer_id: 3975, answer: 'Literate but no formal school/School upto 4 year' },
                { question_answer_id: 3976, answer: 'Middle School' },
                { question_answer_id: 3977, answer: 'Matriculation (10th)' },
                { question_answer_id: 3978, answer: 'Intermediate (12th)' },
                { question_answer_id: 3979, answer: 'Diploma (ITI)' },
                { question_answer_id: 3980, answer: 'Diploma (Polytechnic)' },
                { question_answer_id: 3981, answer: 'Graduate 3-years college (Pass)' },
                { question_answer_id: 3982, answer: 'Graduate 3-years college (Hons)' },
                { question_answer_id: 3983, answer: 'Graduate 4 years' },
                { question_answer_id: 3984, answer: 'Postgraduate Diploma' },
                { question_answer_id: 3985, answer: 'Postgraduate / Masters Degree' },
                { question_answer_id: 3986, answer: 'Vocational Courses' },
                { question_answer_id: 3987, answer: 'Professional Courses' },
                { question_answer_id: 3988, answer: 'Doctorate Degree (Ph.D.)' },
            ],
        },
        {
            profile_survey_question_id: '44',
            question_id: 497,
            order_no: 2,
            question: 'Household Income (Annual)',
            question_type: '2',
            answer_arr: [
                { question_answer_id: 4325, answer: 'Less than ₹50,000' },
                { question_answer_id: 4326, answer: '₹50,000-₹99,999' },
                { question_answer_id: 4327, answer: '₹1,00,000-₹1,99,999' },
                { question_answer_id: 4328, answer: '₹2,00,000-₹4,99,999' },
                { question_answer_id: 4329, answer: '₹5,00,000-₹7,49,999' },
                { question_answer_id: 4330, answer: '₹7,50,000-₹9,99,999' },
                { question_answer_id: 4331, answer: '₹10,00,000-₹14,99,999' },
                { question_answer_id: 4332, answer: '₹15,00,000-₹19,99,999' },
                { question_answer_id: 4333, answer: '₹20,00,000-₹49,99,999' },
                { question_answer_id: 4334, answer: '₹50,00,000-₹99,99,999' },
                { question_answer_id: 4335, answer: '₹1,00,00,000-₹4,99,99,999' },
                { question_answer_id: 4336, answer: '₹5,00,00,000+' },
                { question_answer_id: 48826, answer: 'Do not know' },
                { question_answer_id: 48827, answer: 'Prefer not to say' },
            ],
        },
        {
            profile_survey_question_id: '45',
            question_id: 482,
            order_no: 3,
            question: 'What is your marital status?',
            question_type: '2',
            answer_arr: [
                { question_answer_id: 4253, answer: 'Single / Never Married' },
                { question_answer_id: 4254, answer: 'Married' },
                { question_answer_id: 4255, answer: 'Engaged' },
                { question_answer_id: 4256, answer: 'Widowed' },
                { question_answer_id: 4257, answer: 'Divorced' },
                { question_answer_id: 4258, answer: 'Separated' },
                { question_answer_id: 4259, answer: 'Living with partner' },
                { question_answer_id: 4260, answer: 'Prefer not to say' },
            ],
        },
        {
            profile_survey_question_id: '46',
            question_id: 495,
            order_no: 4,
            question: 'How many pets, if any, do you have?',
            question_type: '6',
            answer_arr: [
                { question_answer_id: 4305, answer: 'None' },
                { question_answer_id: 4306, answer: 'One' },
                { question_answer_id: 4307, answer: 'Two or more' },
            ],
            gird_sub_que_arr: [
                { grid_subquestion_id: 256, subquestion: 'Dog(s)' },
                { grid_subquestion_id: 257, subquestion: 'Cat(s)' },
                { grid_subquestion_id: 258, subquestion: 'Fish' },
                { grid_subquestion_id: 259, subquestion: 'Bird(s)' },
                { grid_subquestion_id: 260, subquestion: 'Horse(s)' },
                { grid_subquestion_id: 261, subquestion: 'Other' },
            ],
        },
        {
            profile_survey_question_id: '47',
            question_id: 516,
            order_no: 5,
            question: 'Do you shop online?',
            question_type: '1',
            answer_arr: [
                { question_answer_id: 4637, answer: 'Yes' },
                { question_answer_id: 4638, answer: 'Yes but not frequently' },
                { question_answer_id: 4639, answer: 'I do not shop online' },
            ],
        },
        {
            profile_survey_question_id: '48',
            question_id: 556,
            order_no: 6,
            question:
                'Do you or any of your family members have got health insurance covered? (Please select all that applies.)',
            question_type: '7',
            answer_arr: [
                { question_answer_id: 5535, answer: 'Self-covered' },
                { question_answer_id: 5536, answer: 'Covered by employer' },
                { question_answer_id: 5537, answer: 'Covered by Government' },
                { question_answer_id: 5538, answer: 'Not covered', key: 'N' },
            ],
            gird_sub_que_arr: [
                { grid_subquestion_id: 282, subquestion: 'For me' },
                { grid_subquestion_id: 283, subquestion: 'For family members' },
            ],
        },
        {
            profile_survey_question_id: '49',
            question_id: 561,
            order_no: 7,
            question:
                'Have you or any of your family members ever been diagnosed with any of the following illnesses/conditions? (Please select all that applies.)',
            question_type: '7',
            answer_arr: [
                { question_answer_id: 5838, answer: 'ADHD' },
                { question_answer_id: 5839, answer: 'Arthritis' },
                { question_answer_id: 5840, answer: 'Asthma' },
                { question_answer_id: 5841, answer: 'Autism Spectrum Disorder (ASD)' },
                { question_answer_id: 5842, answer: 'Avian Influenza (bird flu)' },
                { question_answer_id: 5843, answer: 'Birth Defects' },
                { question_answer_id: 5844, answer: 'Cancer' },
                { question_answer_id: 5845, answer: 'Chlamydia' },
                { question_answer_id: 5846, answer: 'Chronic Fatigue Syndrome' },
                { question_answer_id: 5847, answer: 'Diabetes' },
                { question_answer_id: 5848, answer: 'Digestive conditions' },
                { question_answer_id: 5849, answer: 'Epilepsy' },
                { question_answer_id: 5850, answer: 'Fetal Alcohol Syndrome' },
                { question_answer_id: 5851, answer: 'Flu (Influenza)' },
                { question_answer_id: 5852, answer: 'Genital Herpes (Herpes Simplex Virus)' },
                { question_answer_id: 5853, answer: 'Giardiasis' },
                { question_answer_id: 5854, answer: 'Gonorrhea' },
                { question_answer_id: 5855, answer: 'Heart/Blood Disease' },
                { question_answer_id: 5856, answer: 'Hepatitis' },
                { question_answer_id: 5857, answer: 'HIV/AIDS' },
                { question_answer_id: 5858, answer: 'Human Papillomavirus (HPV)' },
                { question_answer_id: 5859, answer: 'Kidney Disease (Chronic Kidney Disease)' },
                { question_answer_id: 5860, answer: 'Meningitis' },
                { question_answer_id: 5861, answer: 'Methicillin-resistant Staphylococcus aureus (MRSA)' },
                { question_answer_id: 5862, answer: 'Middle East Respiratory Syndrome (MERS)' },
                { question_answer_id: 5863, answer: 'Overweight and Obesity' },
                { question_answer_id: 5864, answer: 'Parasites – Scabies' },
                { question_answer_id: 5865, answer: 'Salmonella' },
                { question_answer_id: 5866, answer: 'Sexually Transmitted Diseases (STDs)' },
                { question_answer_id: 5867, answer: 'Stroke' },
                { question_answer_id: 5868, answer: 'Traumatic Brain Injury (TBI)' },
                { question_answer_id: 5869, answer: 'Trichomonas Infection (Trichomoniasis)' },
                { question_answer_id: 5870, answer: 'Tuberculosis (TB)' },
                { question_answer_id: 5871, answer: 'Water-related Diseases' },
                { question_answer_id: 5873, answer: 'None of the above', key: 'N' },
            ],
            gird_sub_que_arr: [
                { grid_subquestion_id: 287, subquestion: 'Myself' },
                { grid_subquestion_id: 288, subquestion: 'Family member(s)' },
                { grid_subquestion_id: 289, subquestion: 'Someone I care' },
            ],
        },
        {
            profile_survey_question_id: '50',
            question_id: 588,
            order_no: 8,
            question: 'Do you exercise on a regular basis?',
            question_type: '1',
            answer_arr: [
                { question_answer_id: 5965, answer: 'Daily' },
                { question_answer_id: 5966, answer: 'A few times a week' },
                { question_answer_id: 5967, answer: 'A few times a month' },
                { question_answer_id: 5968, answer: 'Rarely' },
                { question_answer_id: 5969, answer: 'Never' },
            ],
        },
        {
            profile_survey_question_id: '51',
            question_id: 579,
            order_no: 9,
            question: 'Do you have any of the following eye conditions?',
            question_type: '1',
            answer_arr: [
                { question_answer_id: 5959, answer: 'Astigmatism' },
                { question_answer_id: 5960, answer: 'Farsightedness/Longsighedness (Hyperopia)' },
                { question_answer_id: 5961, answer: 'Shortsightedness (Myopia)' },
                { question_answer_id: 5962, answer: 'Presbyopia' },
                { question_answer_id: 5963, answer: 'Other' },
                { question_answer_id: 5964, answer: 'I do not have any eye condition' },
            ],
        },
        {
            profile_survey_question_id: '52',
            question_id: 667,
            order_no: 10,
            question: 'Have you travelled by airline within the past 12 months?',
            question_type: '2',
            answer_arr: [
                { question_answer_id: 6216, answer: 'Yes, Domestic only' },
                { question_answer_id: 6217, answer: 'Yes, International only' },
                { question_answer_id: 6218, answer: 'Yes, Domestic and International both' },
                { question_answer_id: 6219, answer: 'I have not travelled by airline within the past 12 months' },
            ],
        },
        {
            profile_survey_question_id: '53',
            question_id: 528,
            order_no: 11,
            question: 'Employment Status',
            question_type: '1',
            answer_arr: [
                { question_answer_id: 4742, answer: 'Full time employed' },
                { question_answer_id: 4743, answer: 'Part time employed' },
                { question_answer_id: 4744, answer: 'Self-employed/Independent Professional/Contractor' },
                { question_answer_id: 4745, answer: 'Between Jobs/Searching for a Job' },
                { question_answer_id: 4746, answer: 'Housewife/Homemaker' },
                { question_answer_id: 4747, answer: 'Military/Defence Services' },
                { question_answer_id: 4748, answer: 'Student' },
                { question_answer_id: 4749, answer: 'Retired' },
            ],
        },
        {
            profile_survey_question_id: '54',
            question_id: 529,
            order_no: 12,
            question: 'What is your primary profession?',
            question_type: '2',
            answer_arr: [
                { question_answer_id: 4750, answer: 'Actor\r' },
                { question_answer_id: 4751, answer: '6-8 Teacher\r' },
                { question_answer_id: 4752, answer: 'Accountant\r' },
                { question_answer_id: 4753, answer: 'Admin executive\r' },
                { question_answer_id: 4754, answer: 'Aeronautical Engineer\r' },
                { question_answer_id: 4755, answer: 'Agricultural advisor\r' },
                { question_answer_id: 4756, answer: 'Agricultural Engineer\r' },
                { question_answer_id: 4757, answer: 'Agronomist\r' },
                { question_answer_id: 4758, answer: 'Air Traffic Controller\r' },
                { question_answer_id: 4759, answer: 'Air-conditioning installer or mechanic\r' },
                { question_answer_id: 4760, answer: 'Aircraft service technician\r' },
                { question_answer_id: 4761, answer: 'Ambulance driver\r' },
                { question_answer_id: 4762, answer: 'Anthropologist\r' },
                { question_answer_id: 4763, answer: 'Aquatic Scientist\r' },
                { question_answer_id: 4764, answer: 'Archaeologist\r' },
                { question_answer_id: 4765, answer: 'Architect\r' },
                { question_answer_id: 4766, answer: 'Architectural Technologist\r' },
                { question_answer_id: 4767, answer: 'Archivist\r' },
                { question_answer_id: 4768, answer: 'Artist\r' },
                { question_answer_id: 4769, answer: 'Assembly Line Worker\r' },
                { question_answer_id: 4770, answer: 'Astronomer\r' },
                { question_answer_id: 4771, answer: 'Auctioneer\r' },
                { question_answer_id: 4772, answer: 'Auditor\r' },
                { question_answer_id: 4773, answer: 'Automotive Body Repairer\r' },
                { question_answer_id: 4774, answer: 'Automotive Electrician\r' },
                { question_answer_id: 4775, answer: 'Bank clerk\r' },
                { question_answer_id: 4776, answer: 'Banker\r' },
                { question_answer_id: 4777, answer: 'Beauty therapist\r' },
                { question_answer_id: 4778, answer: 'Beer Brewer\r' },
                { question_answer_id: 4779, answer: 'Biologist\r' },
                { question_answer_id: 4780, answer: 'Biomedical Engineer\r' },
                { question_answer_id: 4781, answer: 'Blacksmith\r' },
                { question_answer_id: 4782, answer: 'Book Keeper\r' },
                { question_answer_id: 4783, answer: 'Bookbinder\r' },
                { question_answer_id: 4784, answer: 'Bookkeeper\r' },
                { question_answer_id: 4785, answer: 'Botanist\r' },
                { question_answer_id: 4786, answer: 'Bricklayer\r' },
                { question_answer_id: 4787, answer: 'Broker\r' },
                { question_answer_id: 4788, answer: 'Bus Driver\r' },
                { question_answer_id: 4789, answer: 'Business Analyst\r' },
                { question_answer_id: 4790, answer: 'Business Economist\r' },
                { question_answer_id: 4791, answer: 'Butcher\r' },
                { question_answer_id: 4792, answer: 'Car mechanic\r' },
                { question_answer_id: 4793, answer: 'Carpenter\r' },
                { question_answer_id: 4794, answer: 'Cashier\r' },
                { question_answer_id: 4795, answer: 'Chartered Accountant\r' },
                { question_answer_id: 4796, answer: 'Chemical Engineer\r' },
                { question_answer_id: 4797, answer: 'Chemist\r' },
                { question_answer_id: 4798, answer: 'Child carer\r' },
                { question_answer_id: 4799, answer: 'Civil Engineer\r' },
                { question_answer_id: 4800, answer: 'Cleaner\r' },
                { question_answer_id: 4801, answer: 'Clerk\r' },
                { question_answer_id: 4802, answer: 'Clothing Designer\r' },
                { question_answer_id: 4803, answer: 'Cobbler\r' },
                { question_answer_id: 4804, answer: 'Computer Hardware Engineer\r' },
                { question_answer_id: 4805, answer: 'Computer Software Engineer\r' },
                { question_answer_id: 4806, answer: 'Cooling or freezing installer or mechanic\r' },
                { question_answer_id: 4807, answer: 'Costume Designer\r' },
                { question_answer_id: 4808, answer: 'Crane Operator\r' },
                { question_answer_id: 4809, answer: 'Curator\r' },
                { question_answer_id: 4810, answer: 'Customer and Excise Officer\r' },
                { question_answer_id: 4811, answer: 'Dancer\r' },
                { question_answer_id: 4812, answer: 'Database Administrator\r' },
                { question_answer_id: 4813, answer: 'Defence Personnel\r' },
                { question_answer_id: 4814, answer: 'Dental Technician\r' },
                { question_answer_id: 4815, answer: 'Dentist\r' },
                { question_answer_id: 4816, answer: 'Department store manager\r' },
                { question_answer_id: 4817, answer: 'Detective\r' },
                { question_answer_id: 4818, answer: 'Diesel loco Driver\r' },
                { question_answer_id: 4819, answer: 'Dietician\r' },
                { question_answer_id: 4820, answer: 'Draughtsman\r' },
                { question_answer_id: 4821, answer: 'Ecologist\r' },
                { question_answer_id: 4822, answer: 'Editor\r' },
                { question_answer_id: 4823, answer: 'Electrical and Electronic Engineer\r' },
                { question_answer_id: 4824, answer: 'Electrician\r' },
                { question_answer_id: 4825, answer: 'Engineering\r' },
                { question_answer_id: 4826, answer: 'Entrepreneur\r' },
                { question_answer_id: 4827, answer: 'Event Manager\r' },
                { question_answer_id: 4828, answer: 'Executive secretary\r' },
                { question_answer_id: 4829, answer: 'Extractive Metallurgist\r' },
                { question_answer_id: 4830, answer: 'Faculty / Administrator (Education Sector)\r' },
                { question_answer_id: 4831, answer: 'Farmer\r' },
                { question_answer_id: 4832, answer: 'Film/ Movie Producer and Director\r' },
                { question_answer_id: 4833, answer: 'Financial and Investment Manager\r' },
                { question_answer_id: 4834, answer: 'Fire-Fighter\r' },
                { question_answer_id: 4835, answer: 'Flight attendant\r' },
                { question_answer_id: 4836, answer: 'Florist\r' },
                { question_answer_id: 4837, answer: 'Food scientist\r' },
                { question_answer_id: 4838, answer: 'Gardener\r' },
                { question_answer_id: 4839, answer: 'General practitioner\r' },
                { question_answer_id: 4840, answer: 'Geographer\r' },
                { question_answer_id: 4841, answer: 'Geologist\r' },
                { question_answer_id: 4842, answer: 'Graphic Designer\r' },
                { question_answer_id: 4843, answer: 'Hairdresser\r' },
                { question_answer_id: 4844, answer: 'Homeopath Doctor\r' },
                { question_answer_id: 4845, answer: 'Horticulturist\r' },
                { question_answer_id: 4846, answer: 'Hotel / Restaurant / Resort Manager\r' },
                { question_answer_id: 4847, answer: 'Hotel / Restaurant / Resort Owner\r' },
                { question_answer_id: 4848, answer: 'Housekeeper\r' },
                { question_answer_id: 4849, answer: 'HR professional\r' },
                { question_answer_id: 4850, answer: 'HS Teacher\r' },
                { question_answer_id: 4851, answer: 'Human Resource Manager\r' },
                { question_answer_id: 4852, answer: 'Insurance Broker\r' },
                { question_answer_id: 4853, answer: 'Interior Designer\r' },
                { question_answer_id: 4854, answer: 'Jeweller\r' },
                { question_answer_id: 4855, answer: 'Jockey\r' },
                { question_answer_id: 4856, answer: 'Journalist\r' },
                { question_answer_id: 4857, answer: 'Judge\r' },
                { question_answer_id: 4858, answer: 'K-12 Teacher\r' },
                { question_answer_id: 4859, answer: 'K-5 Teacher\r' },
                { question_answer_id: 4860, answer: 'Labourer\r' },
                { question_answer_id: 4861, answer: 'Land Surveyor\r' },
                { question_answer_id: 4862, answer: 'Lawyer\r' },
                { question_answer_id: 4863, answer: 'Legal secretary\r' },
                { question_answer_id: 4864, answer: 'Librarian\r' },
                { question_answer_id: 4865, answer: 'Locksmith\r' },
                { question_answer_id: 4866, answer: 'Logistics manager\r' },
                { question_answer_id: 4867, answer: 'Machine Operator\r' },
                { question_answer_id: 4868, answer: 'Management Consultant\r' },
                { question_answer_id: 4869, answer: 'Manufacturing Engineer\r' },
                { question_answer_id: 4870, answer: 'Marketing Executive\r' },
                { question_answer_id: 4871, answer: 'Marketing Manager\r' },
                { question_answer_id: 4872, answer: 'Mathematician\r' },
                { question_answer_id: 4873, answer: 'Mechanical Engineer\r' },
                { question_answer_id: 4874, answer: 'Mechanical engineering technician\r' },
                { question_answer_id: 4875, answer: 'Medical Doctor\r' },
                { question_answer_id: 4876, answer: 'Meteorologist\r' },
                { question_answer_id: 4877, answer: 'Miner\r' },
                { question_answer_id: 4878, answer: 'Mining Engineer\r' },
                { question_answer_id: 4879, answer: 'Model Builder (Architecture)\r' },
                { question_answer_id: 4880, answer: 'Musical Instrument Player\r' },
                { question_answer_id: 4881, answer: 'Musician\r' },
                { question_answer_id: 4882, answer: 'News Reader\r' },
                { question_answer_id: 4883, answer: 'Nuclear Scientist\r' },
                { question_answer_id: 4884, answer: 'Nurse\r' },
                { question_answer_id: 4885, answer: 'Oceanographer\r' },
                { question_answer_id: 4886, answer: 'Optical Technician\r' },
                { question_answer_id: 4887, answer: 'Optometrist\r' },
                { question_answer_id: 4888, answer: 'Ornithologist\r' },
                { question_answer_id: 4889, answer: 'Painter and Decorator\r' },
                { question_answer_id: 4890, answer: 'Personnel Consultant\r' },
                { question_answer_id: 4891, answer: 'Petroleum Technologist\r' },
                { question_answer_id: 4892, answer: 'Pharmacist\r' },
                { question_answer_id: 4893, answer: 'Photographer\r' },
                { question_answer_id: 4894, answer: 'Physicist\r' },
                { question_answer_id: 4895, answer: 'Physiologist\r' },
                { question_answer_id: 4896, answer: 'Pilot\r' },
                { question_answer_id: 4897, answer: 'Plumber\r' },
                { question_answer_id: 4898, answer: 'Police Officer\r' },
                { question_answer_id: 4899, answer: 'Post Office Clerk\r' },
                { question_answer_id: 4900, answer: 'Potter\r' },
                { question_answer_id: 4901, answer: 'Printing machine operator\r' },
                { question_answer_id: 4902, answer: 'Project Manager\r' },
                { question_answer_id: 4903, answer: 'Psychologist\r' },
                { question_answer_id: 4904, answer: 'Public Relations Practitioner\r' },
                { question_answer_id: 4905, answer: 'Public Servant\r' },
                { question_answer_id: 4906, answer: 'Purchasing Manager\r' },
                { question_answer_id: 4907, answer: 'Quality inspector\r' },
                { question_answer_id: 4908, answer: 'Radio Jockey\r' },
                { question_answer_id: 4909, answer: 'Receptionist\r' },
                { question_answer_id: 4910, answer: 'Researcher (Biotechnology\r' },
                { question_answer_id: 4911, answer: 'Restaurant cook\r' },
                { question_answer_id: 4912, answer: 'Rigger\r' },
                { question_answer_id: 4913, answer: 'Roofer\r' },
                { question_answer_id: 4914, answer: 'Sales Representative\r' },
                { question_answer_id: 4915, answer: 'Salesperson\r' },
                { question_answer_id: 4916, answer: 'Security Officer\r' },
                { question_answer_id: 4917, answer: 'Shop Keeper\r' },
                { question_answer_id: 4918, answer: 'Singer\r' },
                { question_answer_id: 4919, answer: 'Social Worker\r' },
                { question_answer_id: 4920, answer: 'Sportsman\r' },
                { question_answer_id: 4921, answer: 'Statistician\r' },
                { question_answer_id: 4922, answer: 'Tailor\r' },
                { question_answer_id: 4923, answer: 'Technical Writer\r' },
                { question_answer_id: 4924, answer: 'Telecommunication Engineer\r' },
                { question_answer_id: 4925, answer: 'Textile Designer\r' },
                { question_answer_id: 4926, answer: 'Tourism Manager\r' },
                { question_answer_id: 4927, answer: 'Traffic Officer\r' },
                { question_answer_id: 4928, answer: 'Translator\r' },
                { question_answer_id: 4929, answer: 'Travel Agent\r' },
                { question_answer_id: 4930, answer: 'Truck Driver\r' },
                { question_answer_id: 4931, answer: 'TV / Cable Broadcaster\r' },
                { question_answer_id: 4932, answer: 'Typist\r' },
                { question_answer_id: 4933, answer: 'University / College Professor\r' },
                { question_answer_id: 4934, answer: 'Value-Added Reseller or Distributor\r' },
                { question_answer_id: 4935, answer: 'Vehicle Driver\r' },
                { question_answer_id: 4936, answer: 'Veterinary Doctor\r' },
                { question_answer_id: 4937, answer: 'Viticulturists\r' },
                { question_answer_id: 4938, answer: 'Waiter\r' },
                { question_answer_id: 4939, answer: 'Watchmaker\r' },
                { question_answer_id: 4940, answer: 'Weaver\r' },
                { question_answer_id: 4941, answer: 'Welder\r' },
                { question_answer_id: 4942, answer: 'Zoologist\r' },
            ],
        },
        {
            profile_survey_question_id: '402',
            question_id: 532,
            order_no: 13,
            question: 'How many years of work experience do you have (working full-time or part-time)?',
            question_type: '1',
            answer_arr: [
                { question_answer_id: 4995, answer: 'Less than a year' },
                { question_answer_id: 4996, answer: '1-3 years' },
                { question_answer_id: 4997, answer: '3-5 years' },
                { question_answer_id: 4998, answer: '5-10 years' },
                { question_answer_id: 4999, answer: '10-15 years' },
                { question_answer_id: 5000, answer: '15-20 years' },
                { question_answer_id: 5001, answer: '20-25 years' },
                { question_answer_id: 5002, answer: '25-30 years' },
                { question_answer_id: 5003, answer: '30 years and above' },
            ],
        },
        {
            profile_survey_question_id: '55',
            question_id: 530,
            order_no: 14,
            question: 'Which of the following sectors do you work in?',
            question_type: '1',
            answer_arr: [
                { question_answer_id: 4943, answer: 'Public Administration (Federal / Central)' },
                { question_answer_id: 4944, answer: 'Public Administration (State / Provincial)' },
                { question_answer_id: 4945, answer: 'A non-profit organization (NGO)' },
                { question_answer_id: 4946, answer: 'A private (for-profit) company or organization' },
            ],
        },
        {
            profile_survey_question_id: '317',
            question_id: 4594,
            order_no: 15,
            question: 'Enter the name of the organization you are currently working in.',
            question_type: '5',
            answer_arr: [],
        },
        {
            profile_survey_question_id: '403',
            question_id: 533,
            order_no: 16,
            question: 'How long have you been working in your current organization?',
            question_type: '1',
            answer_arr: [
                { question_answer_id: 5004, answer: 'Less than a year' },
                { question_answer_id: 5005, answer: '1-3 years' },
                { question_answer_id: 5006, answer: '3-5 years' },
                { question_answer_id: 5007, answer: '5-10 years' },
                { question_answer_id: 5008, answer: '10-15 years' },
                { question_answer_id: 5009, answer: '15-20 years' },
                { question_answer_id: 5010, answer: '20-25 years' },
                { question_answer_id: 5011, answer: '25-30 years' },
                { question_answer_id: 5012, answer: '30 years and above' },
            ],
        },
        {
            profile_survey_question_id: '56',
            question_id: 531,
            order_no: 17,
            question: 'Which of the following industries you work in?',
            question_type: '2',
            answer_arr: [
                { question_answer_id: 4947, answer: 'Airlines' },
                { question_answer_id: 4948, answer: 'Accounting, auditing, payroll, tax' },
                { question_answer_id: 4949, answer: 'Aerospace' },
                { question_answer_id: 4950, answer: 'Agriculture/ Forestry/ Fishing' },
                { question_answer_id: 4951, answer: 'Automotive' },
                { question_answer_id: 4952, answer: 'Banking' },
                { question_answer_id: 4953, answer: 'Biotechnology/ Life Sciences' },
                { question_answer_id: 4954, answer: 'Business Services/ Consulting' },
                { question_answer_id: 4955, answer: 'Chemicals & Plastics' },
                { question_answer_id: 4956, answer: 'Computer Hardware' },
                { question_answer_id: 4957, answer: 'Computer Software/Services' },
                { question_answer_id: 4958, answer: 'Construction' },
                { question_answer_id: 4959, answer: 'Defence, Military Services' },
                { question_answer_id: 4960, answer: 'Education, Training, Library' },
                { question_answer_id: 4961, answer: 'Electronics' },
                { question_answer_id: 4962, answer: 'Engineering' },
                { question_answer_id: 4963, answer: 'Entertainment, Movies & Media' },
                { question_answer_id: 4964, answer: 'Financial services (other than banking)' },
                { question_answer_id: 4965, answer: 'Food, Beverages & Tobacco' },
                { question_answer_id: 4966, answer: 'Governmental organization, agency or bureau' },
                { question_answer_id: 4967, answer: 'Healthcare: Facilities' },
                { question_answer_id: 4968, answer: 'Hospitality/ Hotels/ Restaurants' },
                { question_answer_id: 4969, answer: 'Industrial & Architecture Design/ Interior Design' },
                { question_answer_id: 4970, answer: 'Information Technology' },
                { question_answer_id: 4971, answer: 'Insurance' },
                { question_answer_id: 4972, answer: 'Internet/E-Commerce' },
                { question_answer_id: 4973, answer: 'Law enforcement or security' },
                { question_answer_id: 4974, answer: 'Legal Services' },
                { question_answer_id: 4975, answer: 'Manufacturing/ Production' },
                { question_answer_id: 4976, answer: 'Market Research' },
                { question_answer_id: 4977, answer: 'Marketing/ Advertising' },
                { question_answer_id: 4978, answer: 'Non-profit, charities, social services' },
                { question_answer_id: 4979, answer: 'Healthcare: Pharmaceuticals' },
                { question_answer_id: 4980, answer: 'Printing & Publishing/ Journalism' },
                { question_answer_id: 4981, answer: 'Real Estate/ Maintenance' },
                { question_answer_id: 4982, answer: 'Retail (General)' },
                { question_answer_id: 4983, answer: 'Retail (Specialty)' },
                { question_answer_id: 4984, answer: 'Sales' },
                { question_answer_id: 4985, answer: 'Science' },
                { question_answer_id: 4986, answer: 'Sports and Recreation' },
                { question_answer_id: 4987, answer: 'Storage Networking' },
                { question_answer_id: 4988, answer: 'Telecommunications' },
                { question_answer_id: 4989, answer: 'Telemarketing/ Call Centres' },
                { question_answer_id: 4990, answer: 'Transportation, Logistics' },
                { question_answer_id: 4991, answer: 'Travel and Tourism' },
                { question_answer_id: 4992, answer: 'Utilities, Energy, Water' },
                { question_answer_id: 4993, answer: 'Veterinary services' },
                { question_answer_id: 4994, answer: 'Wholesale/ Trade' },
                { question_answer_id: 101608, answer: 'Beauty/ Spa/ Personal Care' },
                { question_answer_id: 101609, answer: 'Agribusiness' },
                { question_answer_id: 101610, answer: 'Broadcasting & Cable' },
                {
                    question_answer_id: 101611,
                    answer: 'Graphic Arts/ Commercial Arts/ Product Design/ Production Design',
                },
                { question_answer_id: 101612, answer: 'Distribution & Delivery' },
                { question_answer_id: 101613, answer: 'Healthcare: Product & Supplies' },
                { question_answer_id: 101614, answer: 'Mining & Quarrying' },
                { question_answer_id: 101615, answer: 'Natural Resources & Mining' },
                { question_answer_id: 101616, answer: 'Personal Services: Barber, Photographers, Security, etc.' },
                { question_answer_id: 101632, answer: 'Other' },
            ],
        },
        {
            profile_survey_question_id: '57',
            question_id: 535,
            order_no: 18,
            question: 'How many employees (including you) are employed by your organization?',
            question_type: '1',
            answer_arr: [
                { question_answer_id: 5048, answer: 'Work alone' },
                { question_answer_id: 5049, answer: '2-4 employees' },
                { question_answer_id: 5050, answer: '5-9 employees' },
                { question_answer_id: 5051, answer: '10-19 employees' },
                { question_answer_id: 5052, answer: '20-49 employees' },
                { question_answer_id: 5053, answer: '50-99 employees' },
                { question_answer_id: 5054, answer: '100-249 employees' },
                { question_answer_id: 5055, answer: '250-499 employees' },
                { question_answer_id: 5056, answer: '500-749 employees' },
                { question_answer_id: 5057, answer: '750-999 employees' },
                { question_answer_id: 5058, answer: '1,000-1,499 employees' },
                { question_answer_id: 5059, answer: '1,500-1,999 employees' },
                { question_answer_id: 5060, answer: '2,000-2,499 employees' },
                { question_answer_id: 5061, answer: '2,500-4,999 employees' },
                { question_answer_id: 5062, answer: '5,000-9,999 employees' },
                { question_answer_id: 5063, answer: '10,000-24,999 employees' },
                { question_answer_id: 5064, answer: 'Over 25,000 employees' },
                { question_answer_id: 5065, answer: 'Do not know' },
                { question_answer_id: 5066, answer: 'Prefer not to say' },
            ],
        },
        {
            profile_survey_question_id: '404',
            question_id: 536,
            order_no: 19,
            question:
                'What is the annual turnover of your organization globally? (Please indicate approximate figure.)',
            question_type: '1',
            answer_arr: [
                { question_answer_id: 5085, answer: 'Less than ₹5 lakh' },
                { question_answer_id: 5086, answer: '₹5-10 lakh' },
                { question_answer_id: 5087, answer: '₹10-25 lakh' },
                { question_answer_id: 5088, answer: '₹25-50 lakh' },
                { question_answer_id: 5089, answer: '₹50 lakh-₹1 crore' },
                { question_answer_id: 5090, answer: '₹1-2 crore' },
                { question_answer_id: 5091, answer: '₹2-5 crore' },
                { question_answer_id: 5092, answer: '₹5-10 crore' },
                { question_answer_id: 5093, answer: '₹10-25 crore' },
                { question_answer_id: 5094, answer: '₹25-50 crore' },
                { question_answer_id: 5095, answer: '₹50-100 crore' },
                { question_answer_id: 5096, answer: '₹100-250 crore' },
                { question_answer_id: 5097, answer: '₹250-500 crore' },
                { question_answer_id: 5098, answer: '₹500-1,000 crore' },
                { question_answer_id: 5099, answer: '₹1,000-2,000 crore' },
                { question_answer_id: 5100, answer: '₹2,000-5,000 crore' },
                { question_answer_id: 5101, answer: '₹5,000-10,000 crore' },
                { question_answer_id: 5102, answer: 'More than ₹10,000 crore' },
                { question_answer_id: 5283, answer: 'Do not know' },
                { question_answer_id: 5284, answer: 'Prefer not to say' },
            ],
        },
        {
            profile_survey_question_id: '405',
            question_id: 549,
            order_no: 20,
            question: 'How many computers are there in your organization?',
            question_type: '6',
            answer_arr: [
                { question_answer_id: 5458, answer: '1-4 PC' },
                { question_answer_id: 5459, answer: '5-9 PC' },
                { question_answer_id: 5460, answer: '10-24 PC' },
                { question_answer_id: 5461, answer: '25-49 PC' },
                { question_answer_id: 5462, answer: '50-99 PC' },
                { question_answer_id: 5463, answer: '100-249 PC' },
                { question_answer_id: 5464, answer: '250-499 PC' },
                { question_answer_id: 5465, answer: '500-999 PC' },
                { question_answer_id: 5466, answer: '1000-4999 PC' },
                { question_answer_id: 5467, answer: '5000-9999 PC' },
                { question_answer_id: 5468, answer: '10000-24999 PC' },
                { question_answer_id: 5469, answer: 'Over 25000 PC' },
                { question_answer_id: 5470, answer: 'Do not know' },
                { question_answer_id: 5471, answer: 'Prefer not to say' },
            ],
            gird_sub_que_arr: [
                { grid_subquestion_id: 279, subquestion: 'In Your Office' },
                { grid_subquestion_id: 280, subquestion: 'Globally' },
            ],
        },
        {
            profile_survey_question_id: '59',
            question_id: 541,
            order_no: 21,
            question: 'How would you describe your current title or level in your company?',
            question_type: '1',
            answer_arr: [
                { question_answer_id: 5328, answer: 'C-Level Executive (CEO, CIO, CFO, CTO, Partner, Owner, etc.)' },
                {
                    question_answer_id: 5329,
                    answer: 'High-Level Executive (Senior Vice President, Executive Vice President, etc.)',
                },
                {
                    question_answer_id: 5330,
                    answer: 'Mid-Level (Director of a business unit, division, or department)',
                },
                { question_answer_id: 5331, answer: 'Junior Managerial Level (Manager, Team lead, Supervisor, etc.)' },
                { question_answer_id: 5332, answer: 'Staff or specialist (Analyst, Developer, Account Manager, etc.)' },
                { question_answer_id: 5333, answer: 'Admin / Support Staff' },
                { question_answer_id: 5334, answer: 'Skilled manual worker' },
                { question_answer_id: 5335, answer: 'Semi-skilled / unskilled manual or service worker' },
                { question_answer_id: 5336, answer: 'Other' },
            ],
        },
        {
            profile_survey_question_id: '58',
            question_id: 540,
            order_no: 22,
            question: 'In which department are you currently working in?',
            question_type: '2',
            answer_arr: [
                { question_answer_id: 5305, answer: 'Administration / Management' },
                { question_answer_id: 5306, answer: 'Finance / Accounting' },
                { question_answer_id: 5307, answer: 'Marketing & Advertisement' },
                { question_answer_id: 5308, answer: 'Production / Operations' },
                { question_answer_id: 5309, answer: 'Medical Practitioner' },
                { question_answer_id: 5310, answer: 'Sales & Marketing' },
                { question_answer_id: 5311, answer: 'Executives' },
                { question_answer_id: 5312, answer: 'Human Resources & Personnel / Benefits' },
                { question_answer_id: 5313, answer: 'Purchasing / Procurement' },
                { question_answer_id: 5314, answer: 'Facilities Management' },
                { question_answer_id: 5315, answer: 'IT (Information Technology)' },
                { question_answer_id: 5316, answer: 'Legal' },
                { question_answer_id: 5317, answer: 'Shipping / Mail Services' },
                { question_answer_id: 5318, answer: 'Publishing / Journalism' },
                { question_answer_id: 5319, answer: 'Research & Development / Engineering' },
                { question_answer_id: 5320, answer: 'Customer Services' },
                { question_answer_id: 5321, answer: 'Maintenance' },
                { question_answer_id: 5322, answer: 'Consultants / Advisors' },
                { question_answer_id: 5323, answer: 'Budget & Planning' },
                { question_answer_id: 5324, answer: 'Educators / Faculties' },
                { question_answer_id: 5325, answer: 'Hospitality / Service worker (cleaning)' },
                { question_answer_id: 5326, answer: 'Logistics' },
                { question_answer_id: 5327, answer: 'Other' },
            ],
        },
        {
            profile_survey_question_id: '60',
            question_id: 546,
            order_no: 23,
            question:
                'What best describes your role when it comes to making decisions in your organisation regarding non-IT related matters?',
            question_type: '1',
            answer_arr: [
                { question_answer_id: 5445, answer: 'The sole decision maker' },
                {
                    question_answer_id: 5446,
                    answer: 'Influential in the decision making process and equal share in decision making',
                },
                {
                    question_answer_id: 5447,
                    answer: 'Influential in the decision making process, but not a key decision maker',
                },
                { question_answer_id: 5448, answer: 'Not involved in the decision making process at all' },
                { question_answer_id: 5449, answer: 'Prefer not to answer' },
            ],
        },
        {
            profile_survey_question_id: '61',
            question_id: 547,
            order_no: 24,
            question:
                'Which of the following areas do you cover when it comes to decision making in your organization?',
            question_type: '1',
            answer_arr: [
                { question_answer_id: 5450, answer: 'I make decisions or take part in making decisions related to IT' },
                {
                    question_answer_id: 5451,
                    answer: 'I do not make IT related decisions but influence them significantly',
                },
                { question_answer_id: 5452, answer: 'I neither make nor influence IT related decisions' },
                { question_answer_id: 5453, answer: 'Prefer not to answer' },
            ],
        },
        {
            profile_survey_question_id: '62',
            question_id: 4576,
            order_no: 25,
            question:
                'Which of the following is your most preferred device to take online surveys from Opinion Bureau?',
            question_type: '1',
            answer_arr: [
                { question_answer_id: 82023, answer: 'Desktop/Laptop' },
                { question_answer_id: 82024, answer: 'Tablets' },
                { question_answer_id: 82025, answer: 'Smartphones' },
                { question_answer_id: 82026, answer: 'Others' },
            ],
        },
    ],
};
export default data;
